name: binder_snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - coincbc
  - glpk
  - graphviz
  - mamba
  - matplotlib
  - numpy
  - pandas
  - pip
  - python>=3
  - pyyaml
  - snakemake-minimal
  - seaborn
  - pip:
    - SALib>=1.4.0b0
    - otoole>=1.1.0
