# This file must be named config.yaml and placed in the config/ directory

# Populate the scenarios.csv file with a list of scenario names
# and path (description optional) to the model datapackage
datapackage: scenarios.csv

# Tell the workflow which model results to plot
results: results.csv

# Filetype options: 'csv' or 'parquet' or 'feather'
filetype: csv

# Define the uncertain parameters used to define the Monte Carlo sample
parameters: parameters.csv

# Path to the OSeMOSYS model file
model_file: osemosys_fast.txt

# Choose a solver, choices: 'cbc' or 'gurobi' or 'cplex'
solver: cbc

# Sampling - how large should the sample be?
replicates: 10

# For large models, zip lp file and solution (True/False)
zip: False
