# Populate the scenarios.csv file with a list of scenario names
# and path (description optional)
datapackage: config/scenarios.csv

# Tell the workflow which model results to plot
result_params: config/results.csv
agg_results: config/agg_results.csv

# Define the uncertain parameters used to define the Monte Carlo sample
parameters: config/parameters_simplicity.csv

# Model version
model_file: ../osemosys/OSeMOSYS_GNU_MathProg/src/osemosys_fast.txt

# Sampling - how large should the sample be?
replicates: 2
