modelruns: config/runs.csv
result_params: config/results.csv

model_file: resources/osemosys_short.txt
osemosys_version: abdcef99128bf9632cb25cffdf037dc4dcd9dbab

solver: cbc # choices: currently only cbc. glpk, gurobi and cplex coming...